In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

path = (r"C:\Users\Leem\Downloads\iris.data")
headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.read_csv(path, names = headernames)
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [47]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values
print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [48]:
    # Splitting the dataset into the Training set and Test set  
from sklearn.model_selection import train_test_split
train, test =train_test_split (dataset ,test_size = 0.40)

In [49]:
test.head()

sepal-length  sepal-width  petal-length  petal-width            Class
52            6.9          3.1           4.9          1.5  Iris-versicolor
147           6.5          3.0           5.2          2.0   Iris-virginica
11            4.8          3.4           1.6          0.2      Iris-setosa
101           5.8          2.7           5.1          1.9   Iris-virginica
13            4.3          3.0           1.1          0.1      Iris-setosa

In [50]:
train.head()

sepal-length  sepal-width  petal-length  petal-width            Class
73            6.1          2.8           4.7          1.2  Iris-versicolor
134           6.1          2.6           5.6          1.4   Iris-virginica
44            5.1          3.8           1.9          0.4      Iris-setosa
54            6.5          2.8           4.6          1.5  Iris-versicolor
9             4.9          3.1           1.5          0.1      Iris-setosa

In [51]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size = 0.40)

In [60]:
X_train

array([[-1.31998504,  0.04352972, -1.25476109, -1.33693512],
       [-0.32792948, -0.69103431,  0.63981971,  1.03009755],
       [-1.31998504, -0.20132496, -1.36958417, -1.46843694],
       [-1.19597809, -0.20132496, -1.36958417, -1.33693512],
       [ 1.03614692,  0.04352972,  0.52499663,  0.37258848],
       [-0.57594337,  2.00236714, -1.42699571, -1.07393149],
       [-1.44399198,  0.2883844 , -1.42699571, -1.33693512],
       [-1.07197115,  1.26780311, -1.36958417, -1.33693512],
       [-1.94001976, -0.20132496, -1.54181879, -1.46843694],
       [ 0.78813303, -0.20132496,  1.15652357,  1.29310118],
       [ 0.78813303, -0.69103431,  0.46758509,  0.37258848],
       [ 1.03614692, -0.20132496,  0.69723125,  0.63559211],
       [ 2.27621637,  1.75751247,  1.67322742,  1.29310118],
       [ 0.1680983 ,  0.77809375,  0.41017355,  0.50409029],
       [ 1.5321747 , -0.20132496,  1.21393511,  1.16159937],
       [ 0.54011914,  0.53323908,  0.52499663,  0.50409029],
       [ 0.1680983 , -0.

In [61]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [62]:
len(X_test)

60

In [63]:
len(y_test)

60

In [64]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [65]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [58]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[21  0  0]
 [ 0 15  2]
 [ 0  4 18]]
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        21
Iris-versicolor       0.79      0.88      0.83        17
 Iris-virginica       0.90      0.82      0.86        22

       accuracy                           0.90        60
      macro avg       0.90      0.90      0.90        60
   weighted avg       0.90      0.90      0.90        60

Accuracy: 0.9


TypeError: unsupported operand type(s) for /: 'str' and 'int'